/**
 * Stable, machine-readable error codes returned in the `code` field of every error response.
 * Clients branch on these, so never rename an existing code; add new ones instead.
 */
export enum ErrorCode {
  // Generic
  BAD_REQUEST = 'BAD_REQUEST',
  VALIDATION_FAILED = 'VALIDATION_FAILED',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  NOT_FOUND = 'NOT_FOUND',
  CONFLICT = 'CONFLICT',
  PAYLOAD_TOO_LARGE = 'PAYLOAD_TOO_LARGE',
  UNPROCESSABLE_ENTITY = 'UNPROCESSABLE_ENTITY',
  RATE_LIMITED = 'RATE_LIMITED',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE',
  INVALID_DATE_RANGE = 'INVALID_DATE_RANGE',

  // Authentication
  AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
  AUTH_ACCOUNT_SUSPENDED = 'AUTH_ACCOUNT_SUSPENDED',
  AUTH_REFRESH_TOKEN_INVALID = 'AUTH_REFRESH_TOKEN_INVALID',
  AUTH_REFRESH_TOKEN_REUSED = 'AUTH_REFRESH_TOKEN_REUSED',
  AUTH_EMAIL_NOT_VERIFIED = 'AUTH_EMAIL_NOT_VERIFIED',
  AUTH_VERIFICATION_TOKEN_INVALID = 'AUTH_VERIFICATION_TOKEN_INVALID',
  EMAIL_ALREADY_REGISTERED = 'EMAIL_ALREADY_REGISTERED',
  EMAIL_ALREADY_VERIFIED = 'EMAIL_ALREADY_VERIFIED',
  SESSION_NOT_FOUND = 'SESSION_NOT_FOUND',

  // Users
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  PASSWORD_INCORRECT = 'PASSWORD_INCORRECT',
  PASSWORD_UNCHANGED = 'PASSWORD_UNCHANGED',
  LAST_ADMIN = 'LAST_ADMIN',
  ADMIN_SELF_MODIFICATION = 'ADMIN_SELF_MODIFICATION',

  // Plans, subscriptions and quotas
  PLAN_NOT_FOUND = 'PLAN_NOT_FOUND',
  PLAN_ALREADY_ACTIVE = 'PLAN_ALREADY_ACTIVE',
  PLAN_IS_DEFAULT = 'PLAN_IS_DEFAULT',
  QUOTA_EXCEEDED = 'QUOTA_EXCEEDED',

  // AI providers
  PROVIDER_NOT_FOUND = 'PROVIDER_NOT_FOUND',
  PROVIDER_NAME_TAKEN = 'PROVIDER_NAME_TAKEN',
  PROVIDER_DISABLED = 'PROVIDER_DISABLED',
  PROVIDER_IS_DEFAULT = 'PROVIDER_IS_DEFAULT',
  PROVIDER_MODEL_NOT_ALLOWED = 'PROVIDER_MODEL_NOT_ALLOWED',
  PROVIDER_API_KEY_REQUIRED = 'PROVIDER_API_KEY_REQUIRED',
  PROVIDER_TYPE_UNAVAILABLE = 'PROVIDER_TYPE_UNAVAILABLE',
  PROVIDER_BASE_URL_NOT_ALLOWED = 'PROVIDER_BASE_URL_NOT_ALLOWED',
  NO_DEFAULT_PROVIDER = 'NO_DEFAULT_PROVIDER',
  PROVIDER_AUTH_FAILED = 'PROVIDER_AUTH_FAILED',
  PROVIDER_RATE_LIMITED = 'PROVIDER_RATE_LIMITED',
  PROVIDER_TIMEOUT = 'PROVIDER_TIMEOUT',
  PROVIDER_UNAVAILABLE = 'PROVIDER_UNAVAILABLE',
  PROVIDER_REFUSED = 'PROVIDER_REFUSED',

  // Chat
  CONVERSATION_NOT_FOUND = 'CONVERSATION_NOT_FOUND',

  // Web search
  SEARCH_ENTRY_NOT_FOUND = 'SEARCH_ENTRY_NOT_FOUND',
  SEARCH_ENGINE_UNAVAILABLE = 'SEARCH_ENGINE_UNAVAILABLE',
}
